version: "3.9"
name: local_shedule_service
services:

  shedule_service_db:
    container_name: shedule_service_db
    hostname: shedule_service_db
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_DB_LOGIN}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - "${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}"
    command: [ "postgres", "-c", "max_prepared_transactions=200" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB_NAME} -U ${POSTGRES_DB_LOGIN}" ]
      timeout: 2s
      retries: 15

  shedule_service:
    container_name: shedule_service
    restart: unless-stopped
    build: ..
    working_dir: /code/src
    depends_on:
      shedule_service_db:
        condition: service_healthy
    environment:
      - POSTGRES_DB_LOGIN=${POSTGRES_DB_LOGIN}
      - POSTGRES_DB_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB_HOST=${POSTGRES_DB_HOST}
      - POSTGRES_DB_PORT=${POSTGRES_DB_PORT}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - DSN=${DSN}
    ports:
      - "${APP_PORT}:${APP_PORT}"
